# Generated by Django 2.1.7 on 2019-02-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last online'),
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_connection',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
