version: '3'

services:

  redis:
    image: redis:latest
    #expose:
    #  - "6379"
    ports:
      - "6379:6379"
    networks:
      - app-network

  sockapp:
    restart: always
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    networks:
      - app-network
    command: daphne -b 0.0.0.0 -p 8000 django_sync_users.asgi:application
    # command: daphne -b 0.0.0.0 -p 8000 django_sync_users.asgi:application
    # command: gunicorn --log-level debug --bind 0.0.0.0:8000 django_sync_users.wsgi
    depends_on:
      - redis
    links:
      - redis

  nginxweb:
    restart: always
    image: nginx:1.13
    volumes:
      - ./Docker/config/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - sockapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
